# Generated by Django 5.0.2 on 2024-02-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('batumi', 'Batumi'), ('tbilisi', 'Tbilisi'), ('kutaisi', 'Kutaisi')], default='batumi', max_length=50),
        ),
    ]
