# Generated by Django 5.0.2 on 2024-02-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('city1', 'City 1'), ('city2', 'City 2'), ('city3', 'City 3')], default='city1', max_length=50),
        ),
    ]
