name: Deploy Jekyll and Django

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build Jekyll site
  build_jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload Jekyll artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # Deploy Django application
  deploy_django:
    runs-on: ubuntu-latest
    needs: build_jekyll
    steps:
      # Add steps to set up Django environment, install dependencies, run migrations, and deploy
      # Example:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Django migrations
        run: |
          python manage.py migrate
      # Add steps to deploy Django application to hosting platform (e.g., Heroku, PythonAnywhere)
      # Example:
      - name: Deploy Django application
        run: |
          # Add deployment commands here

  # Deployment job for GitHub Pages
  deploy_jekyll:
    environment:
      name: github-pages
      url: ${{ steps.build_jekyll.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_jekyll
    steps:
      - name: Deploy Jekyll to GitHub Pages
        uses: actions/deploy-pages@v4
